app = "go-grpc-example"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  ENVIRONMENT = "prod"

[[services]]
  internal_port = 9000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [services.ports.tls_options]
    alpn = ["h2"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
