name: Pipeline

on:
  push:
    branches:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: debug
        run: git --no-pager tag

      - name: Install Protobuf compiler
        run: sudo apt install -y protobuf-compiler

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest

      - name: Build
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: go-grpc-example
