name: Release Patch

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Patch Version
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email 'github-actions@github.com'
          bash .build/release_patch.sh
