name: Release Major

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Major Version
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email 'github-actions@github.com'
          bash .build/release_major.sh
